version: '3.2'

services:
  db:
    image: postgres:13.6
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app
    container_name: app
    ports:
      - 5000:5000
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./app:/app
      
